name: Build Image
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Run Build-A-Pando
        run: |
          MACHINE=raspberrypi3-64 ./bap
