name: Build Image
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install Required Tools
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y chrpath diffstat
      
      - name: Run Build-A-Pando
        run: |
          MACHINE=raspberrypi3-64 ./bap
